/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MatrixMultiplier */

#ifndef _Included_MatrixMultiplier
#define _Included_MatrixMultiplier
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MatrixMultiplier
 * Method:    matrix
 * Signature: ([[I[[I[[I)V
 */
JNIEXPORT void JNICALL Java_MatrixMultiplier_matrix
  (JNIEnv *, jobject, jobjectArray, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
